[package]
name = "flowd-unixsocket"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/unixsocket.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for UnixSocketClientComponent
url = "2"
uds = "0.4.2"
