[package]
name = "flowd_component_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "2.0.0", features = ["macros"] }
rtrb = "0.2"
multimap = "0.10.0"
