[package]
name = "flowd-html"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/html.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for HTMLQueryComponent
skyscraper = "0.6.3"
