[package]
name = "flowd-cron"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/cron.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for CronComponent
cron = "0.12.0"
chrono = "0.4.26"
