[package]
name = "flowd-brotli"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/brotli.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for BrotliCompressComponent, BrotliDecompressComponent
brotli = "3.5"
