[package]
name = "flowd-regexp"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/regexp.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for RegexpExtractComponent
regex = "1.10"
