[package]
name = "flowd-hasher"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/hasher.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for HasherComponent
twox-hash = "1.6.3"
