[package]
name = "flowd-xz"
version = "0.1.0+0.4"
edition = "2021"

[lib]
path = "src/xz.rs"

[dependencies]
flowd_component_api = { path = "../../component_api" }
log = "0.4"

# for XzCompressComponent, XzDecompressComponent
xz = "0.1"
